<?php

namespace TutoriaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TutoriaRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TutoriaRepository extends EntityRepository
{
}
